### ISSUE TITLE
youtube tag error

### ISSUE THREAD

**Issue by nhoizey** [ttscoff/JekyllPlugins#1]
I try to use the youtube tag plugin, and get this error:

```
Liquid Exception: undefined method `[]' for nil:NilClass in _posts/2014-06-19-les-super-delires-des-clips-d-ok-go.md
jekyll 2.5.3 | Error:  undefined method `[]' for nil:NilClass
```

Any idea?

**Comment by ttscoff** [comment]
What does your YouTube tag look like?

**Comment by nhoizey** [comment]
Sorry, it works now, and I've changed a lot of things in my code, I don't why it didn't work at the time.
